#!/usr/bin/env python3
"""
Script to generate assets.dart file from all assets in the project
"""
import os
from pathlib import Path

def to_camel_case(s):
    """Convert string to camelCase"""
    # Remove extension
    s = s.rsplit('.', 1)[0] if '.' in s else s
    # Replace special characters with underscore
    s = ''.join(c if c.isalnum() or c in '-_' else '_' for c in s)
    # Split by common separators
    parts = s.replace('-', '_').replace(' ', '_').split('_')
    # Convert to camelCase
    if not parts:
        return s
    return parts[0].lower() + ''.join(word.capitalize() for word in parts[1:] if word)

def generate_asset_name(file_path, base_dir):
    """Generate asset constant name from file path"""
    # Get relative path from assets directory
    rel_path = os.path.relpath(file_path, base_dir)
    # Remove extension
    rel_path_no_ext = os.path.splitext(rel_path)[0]
    
    # Split path
    parts = rel_path_no_ext.split(os.sep)
    
    # Build name
    if len(parts) == 1:
        # Direct file in assets root
        name = to_camel_case(parts[0])
        return f"assets{name.capitalize()}"
    else:
        # File in subdirectory
        category = parts[0]  # e.g., 'logos', 'images', 'icons'
        subcategory = parts[1] if len(parts) > 2 else None
        filename = parts[-1]
        
        # Build name
        name_parts = []
        if category == 'logos' and subcategory:
            name_parts.append('logos')
            name_parts.append(subcategory.capitalize())
            name_parts.append(to_camel_case(filename))
        elif category == 'images' and subcategory:
            name_parts.append('images')
            name_parts.append(subcategory.replace('-', '').capitalize())
            name_parts.append(to_camel_case(filename))
        else:
            name_parts.append(category)
            if subcategory:
                name_parts.append(to_camel_case(subcategory))
            name_parts.append(to_camel_case(filename))
        
        return ''.join(name_parts)

def find_assets(base_dir):
    """Find all asset files"""
    assets = []
    base_path = Path(base_dir)
    
    # Supported extensions
    extensions = {'.png', '.jpg', '.jpeg', '.svg', '.webp', '.ttf', '.json', '.mp4'}
    
    for root, dirs, files in os.walk(base_dir):
        # Skip hidden directories
        dirs[:] = [d for d in dirs if not d.startswith('.')]
        
        for file in files:
            file_path = os.path.join(root, file)
            ext = os.path.splitext(file)[1].lower()
            
            if ext in extensions:
                rel_path = os.path.relpath(file_path, base_path.parent)
                # Normalize path separators
                rel_path = rel_path.replace('\\', '/')
                asset_name = generate_asset_name(file_path, base_path.parent)
                assets.append((asset_name, rel_path))
    
    return sorted(assets, key=lambda x: x[0])

def generate_assets_dart(assets, output_file):
    """Generate assets.dart file"""
    content = """///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

"""
    
    for name, path in assets:
        content += f"  static const String {name} = '{path}';\n"
    
    content += "\n}\n"
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Generated {len(assets)} asset constants in {output_file}")

if __name__ == "__main__":
    assets_dir = "assets"
    output_file = "lib/generated/assets.dart"
    
    if not os.path.exists(assets_dir):
        print(f"Error: {assets_dir} directory not found")
        exit(1)
    
    assets = find_assets(assets_dir)
    
    # Also include i18n files
    i18n_dir = "i18n"
    if os.path.exists(i18n_dir):
        for file in os.listdir(i18n_dir):
            if file.endswith('.json'):
                file_path = os.path.join(i18n_dir, file)
                rel_path = os.path.relpath(file_path, Path(i18n_dir).parent)
                rel_path = rel_path.replace('\\', '/')
                name = f"i18n{file.replace('.json', '').capitalize()}"
                assets.append((name, rel_path))
    
    assets.sort(key=lambda x: x[0])
    
    # Create output directory if it doesn't exist
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    generate_assets_dart(assets, output_file)
